# Generated by Django 2.0.6 on 2018-06-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similar_doctors', '0003_doctor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'doctors'},
        ),
    ]
