# Generated by Django 2.0.6 on 2018-06-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similar_doctors', '0005_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'ratings'},
        ),
    ]
