# Generated by Django 2.0.6 on 2018-06-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similar_doctors', '0006_auto_20180628_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
